name: 'run tests'

on:
  pull_request:
    types:
    - opened
    - synchronize
    branches:
    - master


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3.3.0

    - name: run tests
      run: node --experimental-fetch ./tests.js
